version: '2'

services:
  hubtesting:
    image: selenium/hub:2.52.0
    container_name: your_company-client_hubtesting
    ports:
      - 4444:4444
    networks:
      - project

  chrometesting:
    image: selenium/node-chrome-debug:2.48.2
    container_name: your_company-client_chrometesting
    ports:
      # Port is used for VNC only
      - 5900:5900
      - 5555:5555
    environment:
      - HUB_PORT_4444_TCP_ADDR=hubtesting
    networks:
      - project

  firefoxtesting:
    image: selenium/node-firefox-debug:2.48.2
    container_name: your_company-client_firefoxtesting
    ports:
      # Port is used for VNC only
      - 5901:5900
      - 5556:5555
    environment:
      - HUB_PORT_4444_TCP_ADDR=hubtesting
    networks:
      - project

networks:
  project:
    external:
      name: your_company-client
